from . import help
from . import start
from . import albumHandlar
from . import locationHandler
from . import bankomatHandler
from . import bankHandler
from . import aptekaHandler
from . import hospitalHandler
from . import doc_handler
from . import bankHandler
from . import echo